### ISSUE TITLE
Bug with ChestCheck/Void Vaults/Toggle Collect Chest Items

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/ItemChecklist#11]
There is a bug with counting items from Void Vaults. When 'Toggle Collect Chest Items' is enabled and you open a Void Vault, the game will become unresponsive to keyboard inputs. 

The client.log shows the following error.

[15:00:38.821] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ItemChecklist.ItemChecklistPlayer.ChestCheck() in ItemChecklistPlayer.cs:line 103
   at Terraria.ModLoader.PlayerLoader.PreUpdate(Player player) in tModLoader\Terraria\ModLoader\PlayerLoader.cs:line 186
   at Terraria.Player.Update(Int32 i) in tModLoader\Terraria\Player.cs:line 17966
   at Terraria.Main.DoUpdateInWorld(Stopwatch sw) in tModLoader\Terraria\Main.cs:line 13485
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 13131
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12686
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 546
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 235
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 196
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 52
   at System.Threading.Thread.StartCallback()

**Comment by JavidPack** [comment]
fixed
